name: CI pipeline
on:
  push :
    branches:
      - '**'
  pull_request:
    branches:
      - master
jobs:
  formatting:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          args: "--skip-sorting-imports --replace"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: maven
      - name: Cache SonarQube packages
        uses: actions/cache@v4.0.2
        with:
          path: /.sonar/cache
          key: ${{ runner.os}}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build with Maven
        run:  mvn clean install -DskipTests=true
      - name : Build Docker Image
        run: docker build -t aqua-springboot-be .
      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -Dspring.profiles.active=test-containers -B verify sonar:sonar -Dsonar.projectKey=${{ secrets.SONARQUBE_PROJECT_KEY }} -Dsonar.projectName= ${{ secrets.SONARQUBE_PROJECT_NAME}}
  unitTest:
    runs-on: ubuntu-latest
    needs: build
    env:
      SPRING_DATASOURCE_URL: ${{ secrets.TEST_CONTAINER_URL}}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.TEST_CONTAINER_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.TEST_CONTAINER_PASSWORD }}
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '17'
            cache: maven
        - name: Run tests
          run: mvn test -Dspring.profiles.active=remote-test-containers
